In [62]:
import json

import requests
import pandas as pd

In [26]:
# import argparse
# import json

# import requests
# import pandas as pd


# URL = "https://www.iaa.gov.il/umbraco/surface/FlightBoardSurface/Search"

# session = requests.Session()

# headers = {
#     "User-Agent": "Mozilla/5.0",
#     "X-Requested-With": "XMLHttpRequest",
#     "Origin": "https://www.iaa.gov.il",
#     "Referer": "https://www.iaa.gov.il/airports/ben-gurion/flight-board",
#     "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
# }

# payload = {
#     "g-recaptcha-response": "",
#     "FlightType": "Incoming",   # Change to Outgoing if needed
#     "AirportId": "LLBG",
#     "UICulture": "he-IL",
#     "City": "",
#     "Country": "",
#     "AirlineCompany": "",
#     "FromDate": "1/3/2026",  # You can set date here like "01/03/2026"
#     "ToDate": "7/3/2026",
#     "ufprt": ""  # Leave empty for first test
# }

# response = session.post(URL, headers=headers, data=payload)

# print("Status code:", response.status_code)
# with open("response_iaa.json", "w", encoding="utf-8") as f:
#     f.write(response.text)
# data_iaa = json.loads(response.text)

Status code: 200

In [41]:
gov_api_url = "https://data.gov.il/api/3/action/datastore_search?resource_id=e83f763b-b7d7-479e-b172-ae981ddc6de5"
session = requests.Session()

response = session.get(gov_api_url)
print("Status code:", response.status_code)
with open("data_gov.json", "w", encoding="utf-8") as f:
    f.write(response.text)
data_gov = json.loads(response.text)

Status code: 200

In [3]:
# import json


# with open("response.json", "r", encoding="utf-8") as f:
#         data = json.loads(f.read())

In [42]:
with open("data_gov.json", 'r') as f:
    data_gov = json.loads(f.read())
data_gov.keys()

dict_keys(['help', 'success', 'result'])

In [43]:
len(data_gov['result']['records'])

1920

In [63]:
data_df = pd.DataFrame(data_gov['result']['records'])
incoming = data_df[data_df["CHAORD"] == "A"]
outgoing = data_df[data_df["CHAORD"] == "D"]

In [69]:
result = incoming.groupby("CHLOCCT").agg({"_id": "count"}).sort_values("_id", ascending=False)
result.columns = ["count"]
result["percent"] = (result["count"] / result["count"].sum() * 100).round(2)
result.reset_index().rename(columns={"CHLOCCT": "Country"})

                 Country  count  percent
0   UNITED ARAB EMIRATES    132    14.73
1                 FRANCE     86     9.60
2          UNITED STATES     69     7.70
3                  ITALY     65     7.25
4                  SPAIN     64     7.14
5                GERMANY     57     6.36
6         UNITED KINGDOM     41     4.58
7                 GREECE     39     4.35
8                 ISRAEL     33     3.68
9                GEORGIA     32     3.57
10                POLAND     28     3.12
11               ROMANIA     26     2.90
12           NETHERLANDS     25     2.79
13               HUNGARY     22     2.46
14                CYPRUS     22     2.46
15              ETHIOPIA     20     2.23
16              BULGARIA     18     2.01
17              THAILAND     17     1.90
18           SWITZERLAND     16     1.79
19               AUSTRIA     13     1.45
20        CZECH REPUBLIC     11     1.23
21            AZERBAIJAN      9     1.00
22    RUSSIAN FEDERATION      8     0.89
23               MOLDOVA      7     0.78
24              PORTUGAL      5     0.56
25               BELGIUM      4     0.45
26             LITHUANIA      3     0.33
27                 CHINA      3     0.33
28            UZBEKISTAN      3     0.33
29               FINLAND      2     0.22
30               DENMARK      2     0.22
31                 JAPAN      2     0.22
32               ARMENIA      2     0.22
33            SEYCHELLES      2     0.22
34                CANADA      2     0.22
35               ALBANIA      1     0.11
36              TANZANIA      1     0.11
37                SERBIA      1     0.11
38            MONTENEGRO      1     0.11
39                 INDIA      1     0.11
40               VIETNAM      1     0.11

In [72]:
result.to_csv("incoming_flights_by_country.csv", index=True)

In [65]:
incoming["date"] = incoming["CHPTOL"].str.split("T").str[0]
incoming.groupby("date").agg({"_id": "count"}).sort_values("_id", ascending=False)

            _id
date
2026-03-02  296
2026-03-03  181
2026-03-01  162
2026-03-04  157
2026-03-05  100

In [66]:
incoming[data_df["CHLOCCT"] == "ISRAEL"].count()

/var/folders/4f/zmmsws9j6cn28mxhctd0b4bw0000gn/T/ipykernel_88623/4114147384.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  incoming[data_df["CHLOCCT"] == "ISRAEL"].count()

_id         33
CHOPER      33
CHFLTN      33
CHOPERD     33
CHSTOL      33
CHPTOL      33
CHAORD      33
CHLOC1      33
CHLOC1D     33
CHLOC1TH    33
CHLOC1T     33
CHLOC1CH    33
CHLOCCT     33
CHTERM      33
CHCINT       0
CHCKZN       0
CHRMINE     33
CHRMINH     33
date        33
dtype: int64

In [58]:
(896*200 + 100*100) *0.8

151360.0

In [ ]:
1